### ISSUE TITLE
Spell Check highlight some files and some it doesn't

### ISSUE THREAD

**Issue by cjbischoff** [atom/spell-check#110]
Kinda weird. 
Both files are detected as source.gfm, but one file spell check lint appears and the other doesn't.

Lint package is installed
Default grammars is kept unchanged.

**Comment by lee-dohm** [comment]
I'm confused, you mention "spell check lint" and "Lint package is installed". The spell-check package doesn't depend on any lint or linter package.

In any case, have you followed the suggestions in the [Debugging document](https://atom.io/docs/latest/hacking-atom-debugging)? Also, could you give the following information?

* Which version of Atom are you using?
* What OS and version are you running?
* Can you reproduce the issue after completely exiting Atom and restarting using `atom --safe`?
* Can you give some steps that reproduce this problem?

**Comment by cjbischoff** [comment]
christopher@λ ~ rb:ruby-2.1.6
❯❯❯ atom --version
1.4.3

christopher@λ ~ rb:ruby-2.1.6
❯❯❯ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.5
BuildVersion:	14F1605

I perform the test using running atom --safe and I cannot reproduce the occurrence.

I use atom as a markdown editor and I create files and some documents spellcheck highlights errors in the file and others it does not

**Comment by cjbischoff** [comment]
I run through the packages (disable-restart-check) to see which is the problematic package.

**Comment by lee-dohm** [comment]
Ok, thanks ... let us know what you find!

**Comment by Ben3eeE** [comment]
Thank you for reaching out!

Because this doesn't reproduce in [Safe Mode](http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode), it would seem that what you're reporting isn't being caused by Atom itself but by a community package you have installed. It may be that there is still a bug in Atom. If so, we'll need the maintainer of the package that is causing the problem to help track that down.

What we need you to do is to figure out what community package is causing the problem. Some people have reported that using the [package-cop package](https://atom.io/packages/package-cop) has been helpful, you may want to try it. Once you've determined what package is causing the problem, The [Atom FAQ](https://discuss.atom.io/c/faq) has information on [how to contact the maintainers of any Atom community package or theme](https://discuss.atom.io/t/i-have-a-question-about-a-specific-atom-community-package-where-is-the-best-place-to-ask-it/25581) so you can file this issue there.
