### ISSUE TITLE
windows:Spell Check causes atom to freeze on files thats are 200-500 lines long 

### ISSUE THREAD

**Issue by ungb** [atom/spell-check#190]
### Description

Causes Atom to freeze.  Works when spell-check is disabled
### Steps to Reproduce

1. Download and unzip the file attached here.
[test.zip](https://github.com/atom/spell-check/files/778445/test.zip)

2. Open atom from the directory of the unzip file with spell-check on(it's on by default)
3. Open 2-3 of the files at once

**Expected behavior:** Atom responds quickly and is snappy

**Actual behavior:** Atom freezes up and locks up.  

**Reproduces how often:** [What percentage of the time does it reproduce?]
100%
### Versions
Atom    : 1.14.2
Electron: 1.3.13
Chrome  : 52.0.2743.8
Node    : 6.5.0

Windows 10 x64-bit
### Additional Information
Atom works fine after disabling this package.

**Comment by ungb** [comment]
I don't see this occurring on mac.

**Comment by OvermindDL1** [comment]
Issue is still happening on Windows 10 with Atom version 1.17.2 and spell-check version 0.71.4.

A fairly clean installation, happens sometimes preventing atom from loading, just constantly frozen.
To get Atom working again I either have to `apm disable spell-check` or I have to `atom --clear-window-state` (which I do not like doing since it loses my state...).  If I run `apm disable spell-check` then it is fine again until I re-enable spell-check (where it then instantly freezes permanently until disabled again) or I `atom --clear-window-state`, where then spell-check runs fine when re-enabled until sometime randomly in the next few days when atom is loaded up and it perma-freezes again until the above steps are re-performed.

There are no large files in any open buffer.

**Comment by vvs** [comment]
Can confirm the same problem on Atom 1.18 b3 on Windows 10 x64. Having many files opened, some are small, some are big in the same project causes eventually the hang-up of Atom during startup.

Disabling spell-check package solves the problem!

**Comment by smashwilson** [comment]
@damieng and I fixed the lockups. It'll be in the next beta release :+1:
