### ISSUE TITLE
Builds consistently failing on Travis CI

### ISSUE THREAD

**Issue by jasonrudolph** [atom/spell-check#223]
Starting with https://travis-ci.org/atom/spell-check/builds/286270747 on October 13, 2017, the Travis CI builds are consistently failing.

```
Running specs...
FFFFFFFFFFFFFFFFFFF

Spell check

  when spell checking for a grammar is removed

    it removes all the misspellings

      Expected promise to be resolved, but it was rejected with: ENOTDIR, open '/Users/travis/build/atom/spell-check/atom/Atom.app/Contents/Resources/app.asar/spec/sample.js' { errno : 20, code : 'ENOTDIR', path : '/Users/travis/build/atom/spell-check/atom/Atom.app/Contents/Resources/app.asar/spec/sample.js', syscall : 'open' }

      TypeError: Cannot read property 'setText' of undefined

        at jasmine.Spec.<anonymous> (/Users/travis/build/atom/spell-check/spec/spell-check-spec.coffee:101:13)

...

Finished in 3.454 seconds

19 tests, 38 assertions, 38 failures, 0 skipped
```

**Comment by 50Wliu** [comment]
The fix is to replace https://github.com/atom/spell-check/blob/master/spec/spell-check-spec.coffee#L22 with `atom.workspace.open()`.

This should definitely be fixed as it's affecting other core and community package specs as well.

**Comment by jasonrudolph** [comment]
@50Wliu: Can you say more about why you expect [that change](https://github.com/atom/spell-check/issues/223#issuecomment-338269958) to resolve the build failure? I tried that change locally and [on Travis CI](https://travis-ci.org/atom/spell-check/builds/290608447), and the build still fails, but with a different error:

```
$ apm test
Error Downloading Update: Could not get code signature for running application
FFFFFFFFFFFFFFFFFFF

Spell check
  when spell checking for a grammar is removed
    it removes all the misspellings
      TypeError: Cannot read property 'misspellingMarkersForEditor' of null
        at getMisspellingMarkers (/Users/j/github/spell-check/spec/spell-check-spec.coffee:10:21)
        at jasmine.Spec.<anonymous> (/Users/j/github/spell-check/spec/spell-check-spec.coffee:106:9)
      TypeError: Cannot read property 'misspellingMarkersForEditor' of null
        at getMisspellingMarkers (/Users/j/github/spell-check/spec/spell-check-spec.coffee:10:21)
        at jasmine.Spec.<anonymous> (/Users/j/github/spell-check/spec/spell-check-spec.coffee:110:16)
...
Finished in 2.009 seconds
19 tests, 31 assertions, 29 failures, 0 skipped

Tests failed
```

**Comment by 50Wliu** [comment]
I assume it's because something changed that made `atom.workspace.open`'s cwd default to `/Users/travis/build/atom/spell-check/atom/Atom.app/Contents/Resources/app.asar`.  Then supplying the path tries to append it to app.asar, which gives an ENOTDIR error (because app.asar isn't a directory).  But if you don't supply a path then `atom.workspace.open` doesn't try to give the new file a path (aka an Untitled editor).  See https://github.com/atom/language-go/commit/ca11612f8840c0416543bb8713d13eb65ce0f522 for one example.

**Comment by nathansobo** [comment]
Okay, I finally understand what is happening.

* The legacy spec helper automatically adds the `spec/fixtures` folder as a project path for any package that doesn't have its own fixtures folder.
* This directory isn't shipped as part of our default distribution.
* Previously, when package tests called `atom.workspace.open('sample.js')`, they would not find a path in the non-existent fixtures folder and open a new file with that name instead. Tests that still passed in this situation seemed to not depend on the actual content of sample.js.
* The combination of reintroducing ASAR bundle and reading files in C++ has now caused this problem to emerge. We resolve the `spec/fixtures` path to a path inside the ASAR bundle, but we read this path with low level methods in C++ that are not patched to support ASAR like the Node `fs` methods. This causes us to treat the ASAR bundle as a directory and blow up with an `ENOTDIR` error because it's actually a file, not a directory.

Tomorrow I will try to fix this by automatically setting the project path to some other directory in `/tmp` or something that isn't inside the ASAR bundle. We weren't shipping the fixtures anyway, so this doesn't seem like it could make things worse. 😅

**Comment by olsonpm** [comment]
Probably a case of "same error different cause", but I ran into this as well as an error in atom/style-guide.  This was on a fresh ubuntu vm against the master branch in atom (which contains nathansobo's above fix).  Both times after setting `--enable-electron-logging` a diagnostic error mentioned

```sh
Failed to require the main module of '<module name>' because it requires one or more incompatible native modules...
Run `apm rebuild` in the package directory and restart Atom to resolve.
```

sure enough `apm rebuild` got me going again.

**Comment by 50Wliu** [comment]
@olsonpm yup, your error is different.  Be sure to use `apm install` rather than `npm install` as the two are different.

This issue was fixed back in November.
