### ISSUE TITLE
Spell check cannot be loaded in Atom Beta

### ISSUE THREAD

**Issue by odiousxio2** [atom/spell-check#322]
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by odiousxio2** [comment]
> ### Prerequisites
> * [ ]  Put an X between the brackets on this line if you have done all of the following:
>   
>   * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
>   * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
>   * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
>   * Checked that your issue isn't already filed: [https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Aatom)
>   * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages
> 
> ### Description
> [Description of the issue]
> 
> ### Steps to Reproduce
> 1. [First Step]
> 2. [Second Step]
> 3. [and so on...]
> 
> **Expected behavior:** [What you expect to happen]
> 
> **Actual behavior:** [What actually happens]
> 
> **Reproduces how often:** [What percentage of the time does it reproduce?]
> 
> ### Versions
> You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.
> 
> ### Additional Information
> Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by 9994444ggg** [comment]
Thank You i know that now.But Sorry i dit can do something in the Moment for you. I have to reload my Pc in the Moment after an very big crash by Virus Infection. Sorry

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: odiousxio2<mailto:notifications@github.com>
Gesendet: Mittwoch, 15. April 2020 22:24
An: atom/spell-check<mailto:spell-check@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Betreff: Re: [atom/spell-check] Spell check cannot be loaded in Atom Beta (#322)

Prerequisites

  *   [ ] Put an X between the brackets on this line if you have done all of the following:

     *   Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
     *   Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
     *   Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
     *   Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom<https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+user%3Aatom>
     *   Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

Description

[Description of the issue]

Steps to Reproduce

  1.  [First Step]
  2.  [Second Step]
  3.  [and so on...]

Expected behavior: [What you expect to happen]

Actual behavior: [What actually happens]

Reproduces how often: [What percentage of the time does it reproduce?]

Versions

You can get this information from copy and pasting the output of atom --version and apm --version from the command line. Also, please include the OS and what version of the OS you're running.

Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
