### ISSUE TITLE
error packag sepell-check

### ISSUE THREAD

**Issue by leonardodamata** [atom/spell-check#323]
The package spell-check cannot load the system dictionary for pt_BR. See the settings for ways of changing the languages used, resolving missing dictionaries, or hiding this warning.

**Comment by darangi** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by 9994444ggg** [comment]
Thank You for this Statement
