### ISSUE TITLE
Hunspell personal dictionaries (i.e. exceptions) are not taken into consideration —  is this a bug or a feature? 

### ISSUE THREAD

**Issue by ttasovac** [atom/spell-check#365]
Hi!

I'm on the Mac. With spell-check, I am not using system dictionaries, but a bunch of hunspell dictionaries. Each hunspell dictionary (.aff and .dic) comes with a so-called "personal" dictionary for each locale, i.e. list of exceptions (simple text file, one word per line, no flags etc.). 

These dictionaries are ignored by spell-check in Atom even though they work in hunspell from the command line. I wonder if this is a bug or a feature.

Many thanks in advance.

**Comment by dmoonfire** [comment]
Not using the personal libraries from Hunspell appears to be something of a design decision on [node-spellchecker](https://github.com/atom/node-spellchecker/), probably because it uses different libraries on Macs. It used to only use the built-in Mac spellchecker library until recently (a year ago?) when I added the ability to use Hunspell with a setting. However, even then (and on Linux), the personal libraries are not checked.

**Comment by dmoonfire** [comment]
I'm going to close this. If you want to re-open it again, feel free, but I think it may be something better suited to put on `node-spellcheck` first. Thank you.
